### ISSUE TITLE
what is the hash use for?

### ISSUE THREAD

**Issue by zwxf** [ndevilla/iniparser#106]
Hi, I have some doubt about this project, Does hash is useless in this project?I thought hash is to allocate the key position,but I found this project just use to compare and still compare the key value? is it necessarily or we just only need to compare the key, why need compare the hash value? hoop for your reply,best regards!

**Comment by ndevilla** [comment]
Comparing hashed values is faster than strcmp().
If you have a better hash implementation that actually uses hash values to allocate key positions, it should be fairly easy to plug it in.
