### ISSUE TITLE
Makefile updates conforming to GNU Coding Standards?

### ISSUE THREAD

**Issue by noloader** [ndevilla/iniparser#121]
Hi Nicolas. Sorry for opening a bug report. I did not see contact information on your GitHub account or your homepage.

Would you be interested in some minor modifications to your Makefile that conforms to [GNU Coding Standards](https://www.gnu.org/prep/standards/standards.html)? Specifically, some of the variables in [Section 7.2](https://www.gnu.org/prep/standards/standards.html#Makefile-Conventions)?

Conforming to the GNU standards helps folks on all Linux platforms build and install your software. I believe it will capture the BSD, OS X and Solaris users, too. There may be some outliers, but the differences will be minor.

I read somewhere you were not interested in Makefile changes. (I can't find the page at the moment). I understand arbitrary changes for someone's \<favorite distro here\> are annoying.  However, I think you should consider something that is standardized, like GNU's methods.

**Comment by lmoellendorf** [comment]
Please have a look at [iniparser-meta](https://gitlab.com/iniparser/iniparser-meta).
Feel free to add an issue there if it does not fit your needs.
