### ISSUE TITLE
Null pointer risk

### ISSUE THREAD

**Issue by hangliebe** [ndevilla/iniparser#128]
Trigger point:
```
633： static line_status iniparser_line(
const char * input_line,
char * section,
char * key,
char * value)
{
line_status sta ;
char * line = NULL;
size_t len ;
643： line = xstrdup(input_line);
```
Line 643 passes in the parameter input_line and calls xtrdup to return the pointer of the requested space, but it may return a null pointer.

cause:
```
static char * xstrdup(const char * s)
{
...
len = strlen(s) + 1 ;
t = (char*) malloc(len) ; <----
if (t) {
memcpy(t, s, len) ;
} r
eturn t ; <-----
}
```

The parameter len of malloc is controlled by the parameter and returned directly without non-null verification.

Repair suggestions:
Limit the size of the application space and add non-empty verification.

**Comment by lmoellendorf** [comment]
> Line 643 passes in the parameter input_line and calls xtrdup to return the pointer of the requested space, but it may return a null pointer.

- `iniparser_line()` is a static function which is only called once in [src/iniparser.c](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L803C17-L803C31).
-  its parameter is [`char line    [ASCIILINESZ+1] ;`](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L740)

> The parameter len of malloc is controlled by the parameter and returned directly without non-null verification.

- the parameter `len` of `malloc()` is between 1 and `ASCIILINESZ + 1`  [src/iniparser.c](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L79)](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L79)
- `len` is 1 if `line` contains a leading `'\0'` (empty string)
- if `malloc()` returns `NULL`, `strstrip()` will return 0 [src/iniparser.c](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L79)](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L99)
- if `malloc()` returns a pointer, `memcpy()` will copy the `'\0'` [src/iniparser.c](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L79)](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L82)
- so actually an empty string is passed to `strstrip()` which in turns returns 0 [src/iniparser.c](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L79)](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L111)
- this is recognized as empty line [src/iniparser.c](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L79)](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L671)

> Repair suggestions: Limit the size of the application space and add non-empty verification.

- size of the application is limited:  [`char line    [ASCIILINESZ+1] ;`](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L740)
- non-empty verification is done: [`    if (s==NULL) return 0; `](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L99)

I can see no issue here.

Closing for now. Please correct me, if I missed something, then this may be re-opened.
