### ISSUE TITLE
Preserve case in rewrite

### ISSUE THREAD

**Issue by mcondarelli** [ndevilla/iniparser#129]
I do understand Windows .INI files are supposed to be case-independent, but similar formats are used on Linux where case is usually significant.
Is there any way to preserve case in keys?

**Comment by ndevilla** [comment]
I guess it wouldn't be too hard to implement, but then it would not be an ini file parser, rather a non-standard case-sensitive version of the ini file format. It might break quite a few people's code if keys suddenly become case-sensitive.
One thing could be to add it as a compile-time option that is turned off by default. Pull requests definitely welcome!

**Comment by mcondarelli** [comment]
I will have a look, but we have two different problems here:
1. have an option to set case sensitivity in matching.
2. preserve case **even when** matching is **not** case sensitive.
IMHO `iniparser_load()`/`iniparser_dump_ini()` should *not* change case, even if semantic remains unchanged.
I am more interested in the latter as I plan to use this to build an executable to be used to read/write .INI files from shell.
