### ISSUE TITLE
test_iniparser.c: missing comma in Test_iniparser_getboolean() token_true array declaration

### ISSUE THREAD

**Issue by stevebeattie** [ndevilla/iniparser#131]
https://github.com/ndevilla/iniparser/blob/f858275f7f307eecba84c2f5429483f9f28007f8/test/test_iniparser.c#L458

There's a missing comma in between the "YES" and "Y" entries in the `token_true` array declaration, which will result in the two strings being concatenated and thus the "Y" testcase being skipped.

(This issue was found by coverity.)

**Comment by lmoellendorf** [comment]
Thank you!
