### ISSUE TITLE
Cannot open include file: unistd.h

### ISSUE THREAD

**Issue by HappySeaFox** [ndevilla/iniparser#134]
Hi!

`iniparser` cannot be compiled on Windows with MSVC:

```
fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
```

**Comment by dofuuz** [comment]
You have to use workaround like this:
```
#ifdef __unix__
#include <unistd.h>
#else
typedef long long ssize_t;
#endif
```

Or use my Windows-friendly fork.
https://github.com/dofuuz/iniparser

**Comment by lmoellendorf** [comment]
I am closing this issue since @dofuuz answer seems to solve it - thank you for your contribution.
If this still is an issue, please have a look at [iniparser-meta](https://gitlab.com/iniparser/iniparser-meta) for build-related issues.
