### ISSUE TITLE
Questions about hash function and hash lookup

### ISSUE THREAD

**Issue by SkyAzure** [ndevilla/iniparser#141]
1. The probability of conflict in the design of the hash function is small, but can it be completely avoided? Because the design does not consider the occurrence of hash collision
2. The way to record the traversal of the hash value, whether it is efficient when the amount of data is large

**Comment by ndevilla** [comment]
The design does consider the possibility of hash collision. If the hash matches, the next test uses a strcmp().
See https://github.com/ndevilla/iniparser/blob/master/src/dictionary.c#L220
That said, the hash implementation provided in dictionary.c is not very efficient in terms of memory size or search speed. There are much better options out there, this one is 25 years old.
