### ISSUE TITLE
maximum number  of return value for inparser_getint( )

### ISSUE THREAD

**Issue by e361** [ndevilla/iniparser#142]
Hi, i was wondering this question while  tried to assign this in ini file
-----------------------
[some section]
field1 = 2147483648 or  more (which out of  positive int value)
-----------------------

then i always get  the return value of INT_MAX in program
what i do  for saving the number of uint32_t type  data in ini file.

Heres my question:
1. is it intend to be like this??
2. if there some design purpose or constraint to unsigned int version??
thx for answer.

**Comment by rydercoding** [comment]
I think the designer would like you to call iniparser_getlongint() for larger integer.

**Comment by lmoellendorf** [comment]
> I think the designer would like you to call iniparser_getlongint() for larger integer.

Yes, that is correct. 

@rydercoding 
Thanks for your input.
@e361 
Will close this issue, feel free to ask if you have more questions.
