### ISSUE TITLE
Compiler error on make test

### ISSUE THREAD

**Issue by ricardovalenca** [ndevilla/iniparser#145]
Hello people.

I'm using orange pi and I tried to compile iniparse in Ubuntu, Debian and Armbian version.

With all of them, I'm getting the following output when I run make check:

root@orangepipc:~/iniparser# make check 
make[1]: Entering directory '/root/iniparser/test'
CC      CuTest.o
CC      test_dictionary.o
CC      test_iniparser.o
test_iniparser.c:353:9: warning: integer constant is too large for ‘long’ type [-Wlong-long]
  353 |         { 0x7FFFFFFFFFFFFFFF, "0x7FFFFFFFFFFFFFFF" },
      |         ^
test_iniparser.c:354:9: warning: integer constant is too large for ‘long’ type [-Wlong-long]
  354 |         { -0x7FFFFFFFFFFFFFFF, "-0x7FFFFFFFFFFFFFFF" },
      |         ^
test_iniparser.c:373:5: warning: integer constant is too large for ‘long’ type [-Wlong-long]
  373 |     CuAssertLongIntEquals(tc, 0x7FFFFFFFFFFFFFFF, iniparser_getlongint(dic, NULL, 0x7FFFFFFFFFFFFFFF));
      |     ^~~~~~~~~~~~~~~~~~~~~
test_iniparser.c:373:5: warning: integer constant is too large for ‘long’ type [-Wlong-long]
test_iniparser.c:374:5: warning: integer constant is too large for ‘long’ type [-Wlong-long]
  374 |     CuAssertLongIntEquals(tc, -0x7FFFFFFFFFFFFFFF, iniparser_getlongint(dic, "dummy", -0x7FFFFFFFFFFFFFFF));
      |     ^~~~~~~~~~~~~~~~~~~~~
test_iniparser.c:374:5: warning: integer constant is too large for ‘long’ type [-Wlong-long]
test_iniparser.c: In function ‘void Test_iniparser_getlongint(CuTest*)’:
test_iniparser.c:357:5: warning: narrowing conversion of ‘9223372036854775807’ from ‘long long int’ to ‘long int’ is ill-formed in C++11 [-Wnarrowing]
  357 |     };
      |     ^
test_iniparser.c:353:11: warning: overflow in conversion from ‘long long int’ to ‘long int’ changes value from ‘9223372036854775807’ to ‘-1’ [-Woverflow]
  353 |         { 0x7FFFFFFFFFFFFFFF, "0x7FFFFFFFFFFFFFFF" },
      |           ^~~~~~~~~~~~~~~~~~
test_iniparser.c:357:5: warning: narrowing conversion of ‘-9223372036854775807’ from ‘long long int’ to ‘long int’ is ill-formed in C++11 [-Wnarrowing]
  357 |     };
      |     ^
test_iniparser.c:354:11: warning: overflow in conversion from ‘long long int’ to ‘long int’ changes value from ‘-9223372036854775807’ to ‘1’ [-Woverflow]
  354 |         { -0x7FFFFFFFFFFFFFFF, "-0x7FFFFFFFFFFFFFFF" },
      |           ^~~~~~~~~~~~~~~~~~~
In file included from test_iniparser.c:8:
test_iniparser.c:373:83: warning: overflow in conversion from ‘long long int’ to ‘long int’ changes value from ‘9223372036854775807’ to ‘-1’ [-Woverflow]
  373 |     CuAssertLongIntEquals(tc, 0x7FFFFFFFFFFFFFFF, iniparser_getlongint(dic, NULL, 0x7FFFFFFFFFFFFFFF));
      |                                                                                   ^~~~~~~~~~~~~~~~~~
CuTest.h:87:115: note: in definition of macro ‘CuAssertLongIntEquals’
   87 | #define CuAssertLongIntEquals(tc,ex,ac)           CuAssertLongIntEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
      |                                                                                                                   ^~
test_iniparser.c:373:31: warning: overflow in conversion from ‘long long int’ to ‘long int’ changes value from ‘9223372036854775807’ to ‘-1’ [-Woverflow]
  373 |     CuAssertLongIntEquals(tc, 0x7FFFFFFFFFFFFFFF, iniparser_getlongint(dic, NULL, 0x7FFFFFFFFFFFFFFF));
CuTest.h:87:110: note: in definition of macro ‘CuAssertLongIntEquals’
   87 | #define CuAssertLongIntEquals(tc,ex,ac)           CuAssertLongIntEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
      |                                                                                                              ^~
test_iniparser.c:374:87: warning: overflow in conversion from ‘long long int’ to ‘long int’ changes value from ‘-9223372036854775807’ to ‘1’ [-Woverflow]
  374 |     CuAssertLongIntEquals(tc, -0x7FFFFFFFFFFFFFFF, iniparser_getlongint(dic, "dummy", -0x7FFFFFFFFFFFFFFF));
      |                                                                                       ^~~~~~~~~~~~~~~~~~~
CuTest.h:87:115: note: in definition of macro ‘CuAssertLongIntEquals’
   87 | #define CuAssertLongIntEquals(tc,ex,ac)           CuAssertLongIntEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
      |                                                                                                                   ^~
test_iniparser.c:374:31: warning: overflow in conversion from ‘long long int’ to ‘long int’ changes value from ‘-9223372036854775807’ to ‘1’ [-Woverflow]
  374 |     CuAssertLongIntEquals(tc, -0x7FFFFFFFFFFFFFFF, iniparser_getlongint(dic, "dummy", -0x7FFFFFFFFFFFFFFF));
CuTest.h:87:110: note: in definition of macro ‘CuAssertLongIntEquals’
   87 | #define CuAssertLongIntEquals(tc,ex,ac)           CuAssertLongIntEquals_LineMsg((tc),__FILE__,__LINE__,NULL,(ex),(ac))
      |                                                                                                              ^~
GN      Alltests.c
CC      AllTests.o
CC      testrun
iniparser: cannot open /you/shall/not/path
iniparser: input line too long in ressources/bad_ini/twisted-ofkey.ini (14)
iniparser: input line too long in ressources/bad_ini/twisted-ofval.ini (14)
iniparser: syntax error in ressources/bad_ini/ends_well.ini (5):
-> error is here
iniparser: syntax error in ressources/bad_ini/twisted-errors.ini (5):
-> hello
iniparser: syntax error in ressources/bad_ini/twisted-errors.ini (6):
-> world
iniparser: syntax error in ressources/bad_ini/twisted-errors.ini (8):
-> hello world
iniparser: syntax error in ressources/bad_ini/twisted-errors.ini (9):
-> a + b ;
iniparser: cannot open /path/to/nowhere.ini
.............F......

There was 1 failure:
1) Test_iniparser_getlongint: test_iniparser.c:385: expected <-1> but was <2147483647>

!!!FAILURES!!!
Runs: 20 Passes: 19 Fails: 1

make[1]: *** [Makefile:20: check] Error 1
make[1]: Leaving directory '/root/iniparser/test'
make: *** [Makefile:83: check] Error 2

**Comment by lmoellendorf** [comment]
I can confirm this issue on an ARMv7 platform. 

iniparser assumes that `long int` is 64bit. This is not true for 32bit platforms, where 64bit are `long long int`.

Please note, I am not a maintainer of this project. But you may find a possible solution in my [fork](https://github.com/lmoellendorf/iniparser/tree/bugfix/32bit-architecture).

I also opened a [pull request](https://github.com/ndevilla/iniparser/pull/149).

And I just noticed, there is already a [pull request fixing the tests](https://github.com/ndevilla/iniparser/pull/140). So if you do not need 64bit support on your platform, this would also do.

**Comment by hramrach** [comment]
I suspect your headers are bad. The value is pulled from `limits.h` as `LONG_MAX`, and your `limits.h` header gives you the 64bit value on a 32bit platform.

**Comment by lmoellendorf** [comment]
> I suspect your headers are bad. The value is pulled from `limits.h` as `LONG_MAX`, and your `limits.h` header gives you the 64bit value on a 32bit platform.

Sorry, I don't understand where you are taking this from? I tested on both platforms.

However, meanwhile I cherry-picked your solution as I think it is much smarter than my macros. I only remove the variadic args `...` to get rid of the warning. They are not needed in this particular case.

**Comment by hramrach** [comment]
This part looks like a bad header giving the wrong value for `LONG_MAX`

```
test_iniparser.c:374:87: warning: overflow in conversion from ‘long long int’ to ‘long int’ changes value from ‘-9223372036854775807’ to ‘1’ [-Woverflow]
374 | CuAssertLongIntEquals(tc, -0x7FFFFFFFFFFFFFFF, iniparser_getlongint(dic, "dummy", -0x7FFFFFFFFFFFFFFF));
```

**Comment by lmoellendorf** [comment]
> This part looks like a bad header giving the wrong value for `LONG_MAX`
> 
> ```
> test_iniparser.c:374:87: warning: overflow in conversion from ‘long long int’ to ‘long int’ changes value from ‘-9223372036854775807’ to ‘1’ [-Woverflow]
> 374 | CuAssertLongIntEquals(tc, -0x7FFFFFFFFFFFFFFF, iniparser_getlongint(dic, "dummy", -0x7FFFFFFFFFFFFFFF));
> ```

Are your referring to the compiler error in this message? A sorry, I misunderstood you. I am not the OP of this issue. I just solved it.

**Comment by lmoellendorf** [comment]
I think this one may be closed now. 

@ricardovalenca
Please tell us if this error still persists with latest master.
@hramrach 
Thanks for your contribution.
