### ISSUE TITLE
Parsing surprise for values inside of tick or quote marks

### ISSUE THREAD

**Issue by jonesmz** [ndevilla/iniparser#19]
When a value is inside of a tick mark or a quote mark, and there is a leading or trailing space inside of the enclosing marks, the user is most likely to expect the leading or trailing space to stay attached to the value until the application consuming the iniparser library receives the value.

Instead, lines 581 -> 595 will uniformly strip leading and trailing spaces from values inside of quote/tick marks.

A possible way to resolve this is:

    else if(sscanf (line, "%[^=] = \"%[^\"]\"", key, value) == 2
         || sscanf (line, "%[^=] = '%[^\']'",   key, value) == 2)
    {
        /* Usual key=value inside of tickmarks or quote marks, with or without comments */
        strcpy(key, strstrip(key));
        strcpy(key, strlwc(key));
        //Don't want to strstrip the value, because the user put a space inside the ticks delibrately.
        //strcpy(value, strstrip(value));
        /*
         * sscanf cannot handle '' or "" as empty values
         * this is done here
         */
        if (!strcmp(value, "\"\"") || (!strcmp(value, "''")))
        {
            value[0]=0 ;
        }
        sta = LINE_VALUE ;
    }
    else if(sscanf (line, "%[^=] = %[^;#]",     key, value) == 2)
    {
        /* Usual key=value inside of tickmarks or quote marks, with or without comments */
        strcpy(key, strstrip(key));
        strcpy(key, strlwc(key));
        strcpy(value, strstrip(value));

        sta = LINE_VALUE ;
    }

**Comment by DelusionalLogic** [comment]
For the record, The issue with leading and trailing spaces has been resolved. The issue with dumping ini files not having quotes around certain valued have not.

One possible (easy) fix would be to simply include quotes around all values when dumping.

**Comment by touilleMan** [comment]
fix with commit d224e57
