### ISSUE TITLE
Memory leak with iniparser_getseckeys()

### ISSUE THREAD

**Issue by mikefoss** [ndevilla/iniparser#30]
Hello,

I believe there is a memory leak if you use the function iniparser_getseckeys(). The function description correctly states that none of the actual keys should be free()d, but the char ** reference itself is malloc()ed and never free()d within the library. Please let me know if I am mistaken. I came across this when running valgrind on my application that uses iniparser.

Thank you for such a great tool!

Best,
Mike Foss

**Comment by touilleMan** [comment]
For the v4.0 release, I've change the signature of this function to take a allocated array where to store the keys as argument.
