### ISSUE TITLE
Making the library thread-safe

### ISSUE THREAD

**Issue by mikefoss** [ndevilla/iniparser#31]
I have been using iniparser for a project I am working on, and it is working great. However, I ran into a segmentation fault recently and discovered that the library as written is not thread-safe. The functions strlwc() and strstrip() in iniparser.c are the culprits as they are not re-entrant (as indicated in the comments).

I think that the library documentation should be revised to indicate that it is not currently thread-safe.

However, I have also revised the above functions to take additional arguments that do make them thread-safe. The changes to the rest of the library are transparent to the user. I can send you a patch if you would like.

Best,
Mike Foss

**Comment by bostjan** [comment]
This has not been integrated yet, right?

b.

**Comment by touilleMan** [comment]
You should have a look at my branch https://github.com/touilleMan/iniparser4 ;-)

**Comment by bostjan** [comment]
I see, tnx. :)

It's kinda hard to keep track of where the development is actually going on.

Judging by the diagram at the https://github.com/ndevilla/iniparser/network I can assume quite some development is going on in various repositories but many changes are not pulled back to ndevillea's "main" repository.

Maybe someone should step up and encourage merging all the scattered changes. Unless ndevilla is you :)

b.

BTW I saw this on your repo page: "This branch is 27 commits ahead, 22 commits behind ndevilla:master" - being behind, are you intending to merge those 22 commits or are they incompatible with your changes?

**Comment by touilleMan** [comment]
Cutting a long story short, at the time I wanted to make iniparser evolve, @ndevilla had no time to work on this project and was willing to keep the repo as it is (for backward compatibility), letting me forking the repo to create new major version.

My major changes:
 - unittests with travis integration (code coverage around 92% of dictionary.c and 70% of iniparser.c)
 - constify the api
 - make it thread safe

I the meantime, @ndevilla go back to work and start integrate PR redundant with my changes (constify and thread safe), hence our two repos have diverged.

Of course it would be better to have my branch merged into the main one (at least the unit test part, everybody love unit tests !), but no one has the courage to do it so far... ^^

**Comment by ndevilla** [comment]
Just had a lengthy discussion with touilleMan. He is taking over maintenance of this project in his branch iniparser4. This repository will mostly remain untouched and left for historical purposes. Please address him any further modifications you might want to contribute!

Will update the project page accordingly. Many thanks to all contributors!
Cheers
Nicolas

**Comment by bostjan** [comment]
Thanks for clarification, and thanks for a great library - I am using it for Snoopy (https://github.com/a2o/snoopy ) quite successfully.

b.

**Comment by bostjan** [comment]
@touilleMan: Could you please enable Issues functionality in your iniparser4 project? :)
