### ISSUE TITLE
change something for support win & linux

### ISSUE THREAD

**Issue by freeeyes** [ndevilla/iniparser#46]
thank for your contribute， your code is cool!
but compile at windows have some problem, i change some code for support win & linux.
(VS2008 & g++ (GCC) 4.4.6) compile pass and run ok.
code at here
https://github.com/freeeyes/PSS/tree/master/purenessscopeserver/purenessscopeserver/example-Module/TcpTest/IniRead
and thinks for you code.

**Comment by ndevilla** [comment]
Should work now since previous code merge. Please check!
