### ISSUE TITLE
Please remove `xstrdup()` from public API

### ISSUE THREAD

**Issue by ensc** [ndevilla/iniparser#48]
dictionary.h provides an `xstrdup()` function.  This function name is very generic and it is very likely that a project wants to implement an own `xstrdup()` function.

I suggest to change its name to something like `iniparser_xstrdup()` to avoid such conflicts.

**Comment by ndevilla** [comment]
I will leave that to people who encounter such name clashes. These are just two pages of code, easy enough to modify when needed.
