### ISSUE TITLE
Add a FAQ to the README

### ISSUE THREAD

**Issue by touilleMan** [ndevilla/iniparser#55]
I'm thinking about a copy-paste of the last discussed issue:

### Is Iniparser thread safe ?

Starting from version 4, iniparser is designed to be thread-safe, provided you surround it with your own mutex logic.
The choice not to add thread safety inside the library has been done to provide more freedom for the developer, especially when dealing with it own custom reading logic (i.g. acquiring the mutex, reading plenty of entries in iniparser, then releasing the mutex).

### Your build system isn't portable, let me help you...

I have received countless contributions from distrib people to modify the Makefile into what they think is the "standard", which I had to reject.
The default, standard Makefile for Debian bears absolutely no relationship with the one from SuSE or RedHat and there is no possible way to merge them all.
A build system is something so specific to each environment that it is completely pointless to try and push anything that claims to be standard. The provided Makefile in this project is purely here to have something to play with quickly.

@ndevilla  Do you see any other point to talk about ?

**Comment by ndevilla** [comment]
Sounds good. Don't include my rant on autotools, a README is not the right
place to start a holy war :-)

**Comment by touilleMan** [comment]
Yeah, I intentionally skipped this part ^^

**Comment by touilleMan** [comment]
aaaand done ! (see b1c4ac6fe0ff717f3195da2fbba486a4ababad48)
