### ISSUE TITLE
Would you accept patches moving to Autotools?

### ISSUE THREAD

**Issue by hartwork** [ndevilla/iniparser#62]
Hi!

I noticed that the iniparser maintainer in Gentoo wrote a simple autotools build system for iniparser to apply that as a patch, see https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/dev-libs/iniparser/files/iniparser-3.0-autotools.patch?view=markup .

I'd be happy to port that to iniparser 4.0 as a pull request for you if there is any chance to have it accepted, in general. Personally, I would consider that a good move. What do you think?

Best, Sebastian

**Comment by touilleMan** [comment]
Hi,

First, thanks for your attention on this project :+1: 

However the build system is a touchy problem (see https://github.com/ndevilla/iniparser/issues?utf8=%E2%9C%93&q=build+system), in a nutshell the project is really simple (4 files...) and on the other side each distribution seems to have different needs.

Thus it appears much simpler to provide the project with regular makefile (way more readable than an autotools) that can be use as a base to create a more complex build system depending of the needs (distrib package, integration into a bigger project etc...)

**Comment by hartwork** [comment]
Hi, thanks for a quick answer and the links.

While I do like plain Makefile in general, I believe picking a build system in favour of other people _bundling_ iniparser rather than distributing a _package_ of iniparser to depend on is support in the wrong direction since each distro will have to resolve bundling again anyway, see https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies for details.

That being said, it was probably also a mistake on Gentoo side to write a new build system without having upstream migrate to it, before. So I will drop the autotools system and focus on fixing bugs in the Makefile, if any.

**Comment by hartwork** [comment]
I have completed packaging of iniparser 4.0 including needed patches now. If you are curious, the Ebuild and patches can be found at https://bugs.gentoo.org/show_bug.cgi?id=556774 .

Packaging ended up way more tedious and wordy than with other projects of this size due to lack of an install target (that some build system -- like autotools -- would have offered out of the box). Basically, it forced me to write my own install target (which is most of the current Ebuild) and it forces other Linux distros to do, as well.
