### ISSUE TITLE
Please make 4.0 visible at http://ndevilla.free.fr/iniparser/index.html

### ISSUE THREAD

**Issue by hartwork** [ndevilla/iniparser#63]
Maybe even upload the 4.0 tarball up there, too. Right now, for distro package maintainers its very easy to overlook that there are post-3.1 releases. Thanks!

**Comment by ndevilla** [comment]
Bit hard for me right now, but will do in September. Kick me again if you don't see any change by then :-)
Cheers

**Comment by touilleMan** [comment]
@ndevilla any time to do it ?

**Comment by ndevilla** [comment]
Ok so I updated the home page at free.fr to point out more obviously to this repository on github. I'd rather not delete the tarballs there as some distribution depend on it. They are now all clearly indicated as 'obsolete'. Putting a 4.0 tarball will not help so much as people would certainly miss the latest version. Better follow the project on github.
Let me know if that suits you guys.

**Comment by hartwork** [comment]
Thanks for making adjustments to the page. The reader may look for things he expects though, find heading "Downloads" and filenames and conclude that 3.1 is the latest version (which he/she could be blamed for or not depending on view). To even read the explaining text I would argue, the user needs a reason to assume otherwise *by him- or herself already*.
To really fix the problem (meaning getting the message that 3.1 is not the latest release to 99% of people seeing that page with limited time and attention) I would suggest to go further. Some ideas:
* Rename "Downloads" to "Old downloads" (on a side note, an "archive" could still hold the latest tarball so I would avoid that word) -- may help but may not be enough
* Explicitly mention "4.0 and later" in close proximity to occurrences of 3.1
* Remove the change log and download listing altogether. You can still keep the URLs working (and I vote for that too). It would make the page always up to date automatically as a side effect.

**Comment by ndevilla** [comment]
Just increased message size to make it impossible to overlook that development is now taking place on github. If people don't read web pages there is little more I can do.

**Comment by hartwork** [comment]
It's a lot better now. Thanks!
