### ISSUE TITLE
Makefile: Please drop adding -O2/-g to CFLAGS or make it optional

### ISSUE THREAD

**Issue by hartwork** [ndevilla/iniparser#64]
Hi!

Right now, the Makefile appends either -O2 or -g:
```
ifndef DEBUG
CFLAGS += -O2
else
CFLAGS  += -g
endif
```
It would be cool if you could support a away to have _neither_ happen since it takes away control from the user who may want `-Os` but none of these, for example. Any chance?
Thank you!

Best, Sebastian

**Comment by hartwork** [comment]
Thanks!

**Comment by touilleMan** [comment]
I've added a new variable `ADDITIONAL_CFLAGS` than can be overloaded

```
$ make check V=1
cc -fPIC -Wall -Wextra -ansi -pedantic -O2   -c -o src/iniparser.o src/iniparser.c
[...]
$ make check V=1 ADDITIONAL_CFLAGS=-Os
cc -fPIC -Wall -Wextra -ansi -pedantic -Os   -c -o src/iniparser.o src/iniparser.c
[...]
$ make check V=1 ADDITIONAL_CFLAGS=
cc -fPIC -Wall -Wextra -ansi -pedantic   -c -o src/iniparser.o src/iniparser.c
[...]
```

ps: so quick ! I didn't eve have time to post this explanation ;-)

**Comment by hartwork** [comment]
Yes, got the idea. Works well for packaging.
