### ISSUE TITLE
Makefile: target "libiniparser.so" producing file libiniparser.so.0, actually

### ISSUE THREAD

**Issue by hartwork** [ndevilla/iniparser#65]
Hi!

The current `Makefile` has a target `libiniparser.so` that actually produces `libiniparser.so.0`, rather than `libiniparser.so`:
```
libiniparser.so:	$(OBJS)
	$(QUIET_LINK)$(SHLD) $(LDSHFLAGS) $(LDFLAGS) -o $@.0 $(OBJS) \
		-Wl,-soname=`basename $@`.0
```
If that mismatch is intended, a line `.PHONY: libiniparser.so` is missing to tell make about it.
If not, please use `libiniparser.so.0` or even `libiniparser.so.$(SONAME_CURRENT)` for a target name, instead. Thanks!

Best, Sebastian

**Comment by hartwork** [comment]
Excellent!

Out of curiosity, what's the rationale behind keeping `libiniparser.so` a phony target?

**Comment by touilleMan** [comment]
I guess I didn't fully catch the idea behind

> libiniparser.so.$(SONAME_CURRENT) for a target name, instead

I've made another fix to remove this useless .PHONY and replace the SONAME_CURRENT by a more generic SO_TARGET (for example for people who just want to do `SO_TARGET=libiniparser.so`)

**Comment by hartwork** [comment]
Excellent!
