### ISSUE TITLE
Can't compile on Windows

### ISSUE THREAD

**Issue by DonChunior** [ndevilla/iniparser#74]
I wanted to try the INI parser in a Windows application.
But compiling it was not possible, as the include file unistd.h could not be found (used in your include file dictionary.h).
So the parser is not really portable yet.

**Comment by touilleMan** [comment]
You're profile picture seems so consistent with your last sentence :trollface: 

You can compile on windows with [MinGW](http://www.mingw.org/)

Another method (tough I didn't try it) would be to provide your own `unistd.h` which only imports `io.h`.

**Comment by touilleMan** [comment]
@DonChunior can I close the issue or do you need more help ?

**Comment by DonChunior** [comment]
I haven't tried it anymore.
If you want, you can close the issue, thanks.
