### ISSUE TITLE
Multiline value with comment

### ISSUE THREAD

**Issue by arbego** [ndevilla/iniparser#83]
Hello,

I just noticed that this multine value:

    pizza=yes \
        no \
        maybe \ ; comment for this line only
        i dont know

will result in this after being parsed:

    yes no maybe \

It will ignore the last line `i dont know` because of the comment in the previous line. Also the `\` at the end of the line will be part of the parsed value.

Is this this behaviour expected when adding comments to multine values?

**Comment by lmoellendorf** [comment]
> Is this this behaviour expected when adding comments to multine values?

Yes, I think it is expected. The backslash `\` in a multiline comment is escaping the line feed `LF` character.

```ini
pizza=yes \
    no \
    maybe \ ; comment for this line only
    i dont know
```
In the third line of your example, the backslash is not followed by linefeed , but by `;` which is indicating the start of a comment.
In this respect Iniparser's behavior is in line with the  [Line Continuation  in C](https://www.gnu.org/software/c-intro-and-ref/manual/html_node/Line-Continuation.html). The two examples below will give you errors in C:

```c
	const char test[] = "this is a test " \
						 "about multiline " \// comment
						 "values";
```
```c
#define test this is a test \
	about multiline \//comment
	values
```
