### ISSUE TITLE
fprintf function is  too slow when save something to file

### ISSUE THREAD

**Issue by SmartFrogFromChina** [ndevilla/iniparser#84]
In `iniparser_dump_ini()` and `iniparser_dumpsection_ini()`, the author uses `fprintf` to save ini data to file. When I use those functions ,I found it took me 7~8 seconds every time to save all info to a file.  My embedded platform is MIPS and OS  is Nuttx. After a long period of debugging, I used  `sprintf `and `fwrite `to replace `fprintf`. Then it only took me 1 second to save completely. So I feel that I have the duty to report this .

在函数 iniparser_dump_ini() 和 iniparser_dumpsection_ini() 中，作者使用fprintf函数来保存数据到文件。当我用libiniparse库的时候，我发现每次将数据保存到文件都需要5~6秒。我的平台是MIPS，系统是Nuttx。经过一段时间的调试，我用sprintf来格式化数据，然后用fwrite将数据写入文件，这种方式只需要不到1秒钟的时间。我感觉我有责任来报告一下这个问题。

**Comment by touilleMan** [comment]
你好，中国聪明青蛙 ;-)

Thank for the report, it is possible you platform is forcing buffer flush when using fprintf (for example each time it encounter a `\n`, which should not be the case given normally file are block buffered).

I guess you should be able to use `setbuf` to change the buffer behavior of you file (this could even improve the performances of you current fix by setting a bigger buffer)

下个错误见 !

**Comment by pacepi** [comment]
@touilleMan 
If we add **setvbuf(f, NULL, _IOFBF, 0)** before writing key-value to file, we can resolve this problem.
SmartFrogFromChina is not the only person who met this problem~
I have checked glibc source code, setvbuf() function should be fully supported.

**Comment by touilleMan** [comment]
Thanks for the feedback @pacepi 

@ndevilla do you thing this is worth mentioning in the faq ?

**Comment by pacepi** [comment]
@touilleMan 
I do not think setvuf() or setvbuf is usual API. I have meet performance degradation causing by '\n' for several times.   Orz
If possible, calling setvbuf by libiniparser is a simple and effective way~

**Comment by ndevilla** [comment]
I would avoid calling setvbuf() from iniparser itself, rather recommend the caller does it before writing to a file.
Seems a bit platform-specific to me, but certainly worth mentioning in the FAQ.
Let me add an FAQ here where this kind of thing could be detailed and documented. There are certainly other platforms with buffering issues and such.

**Comment by touilleMan** [comment]
> Let me add an FAQ here

@ndevilla remember we have a faq section in the readme then :smile:

**Comment by ndevilla** [comment]
I know :-) Maybe better to have a separate file? I let you decide.

**Comment by touilleMan** [comment]
I think so far the number of questions are small enough to be kept on the README (gave them more visibility this way)

**Comment by pacepi** [comment]
@ndevilla @touilleMan 
I'd like to translate the FAQ to Chinese. It seems like that a lot of Chinese developer like libiniparser~
Could I make a pull request ?

**Comment by touilleMan** [comment]
@pacepi 行！汉语翻译是一个非常好的思想！^^

**Comment by ndevilla** [comment]
Beautiful idea! Worth detaching the FAQ to a separate file to ease translation, then. Let me commit a first draft by copying the relevant parts from README.

**Comment by ndevilla** [comment]
@touilleMan added FAQ-en.md and modified README to add a pointer. Let me know if this works for you. @pacepi A MILLION THANKS FOR THIS!

**Comment by touilleMan** [comment]
@ndevilla I've added a url link on the faq in the README

**Comment by pacepi** [comment]
@touilleMan @ndevilla 
I had made a pull-request #87 .
Should I do anything else?

**Comment by touilleMan** [comment]
@pacepi you should allow yourself a beer for the great work ;-)
