### ISSUE TITLE
hit an unusual bug when using some config file without any section

### ISSUE THREAD

**Issue by pizhenwei** [ndevilla/iniparser#88]
I have hit an unusual bug when using some config file without any section.
**cat nosec.ini**
hello=world
iniparser=good

I set hello as "newworld", and dump key-value to a new file.
**cat dump.ini**
:hello=newworld
:iniparser=good

@ndevilla 
I had made a pull request to fix the bug #86 .
How do you think about it?

**Comment by philrandal** [comment]
Here's the proper fix:

https://github.com/philrandal/iniparser/commit/f43c08570034583d366d9787623cd9e6a614dcb3
