### ISSUE TITLE
memory leak: dump_buff

### ISSUE THREAD

**Issue by ennorehling** [ndevilla/iniparser#92]
I believe this is leaking the memory allocated for dump_buff.

https://github.com/ndevilla/iniparser/blob/0a38e85c9cde1e099ca3bf70083bd00f89c3e5b6/test/test_dictionary.c#L126

**Comment by arbego** [comment]
It is surrounded by
`if (dump_buff == NULL) {
...
}`

If `calloc` returns NULL, no memory was allocated, hence nothing gets leaked.

**Comment by lmoellendorf** [comment]
Fixed with #151
