### ISSUE TITLE
Support for duplication Sections/Keys

### ISSUE THREAD

**Issue by h4tr3d** [ndevilla/iniparser#96]
Hi,

I have a file seems like:
```
[Section]
  Key = value1
  Key = value2
```
Currently iniparser loads only last value. I suggest to load it as list, like:
```
[Section:Key]=[value1;value2]
```

Another solution, append non-unique Keys with index value and extend API to inform how many keys with given name is present:
```
[Section:Key:0]=[value1]
[Section:Key:1]=[value2]
or (to avoid conflict with real names)
[Section:Key][0]=[value1]
[Section:Key][1]=[value2]
```
and
```
// key: section:key
int iniparser_getnkeys(const dictionary * dict, const char * key);
```
usage:
```
int n1 = iniparser_getnkeys(dict, "Section:Key");
// n1 == 2 
```

after that `key` definition can be extended like:
```
section:key[index]
```

Access without `index` pointing should be refer to zero element. Also, it will be good, that zero element will be accessible for unique keys too.

**Comment by lmoellendorf** [comment]
After checking with @ndevilla I will close this issue.

iniparser supports  having one property with a given name in a section. Support for multiple properties with the same name as requested here is not planned to be supported.

> I have a file seems like:
> 
> ```
> [Section]
>   Key = value1
>   Key = value2
> ```
> 
> Currently iniparser loads only last value.

I can confirm this behaviour.  

Quoting @ndevilla :

> In general we try not to change the API nor the library behaviour.
