### ISSUE TITLE
iniparser_dump_ini() does not protect values when writing back to INI file.

### ISSUE THREAD

**Issue by JaniPajarinen** [ndevilla/iniparser#97]
Problem is when iniparser_dump_ini() function is called, it will save values without enclosing them with '' or "" marks even if in original file had them around values.

This will cause that if data has ; or # characters they will be sanitized away in next load.

I wrote test case to demonstrate the issue -> https://github.com/JaniPajarinen/iniparser/tree/save_load_test

And fix -> https://github.com/JaniPajarinen/iniparser/tree/save_load_fix

**Comment by lmoellendorf** [comment]
See #160
