### ISSUE TITLE
Provide a conanical header installation path

### ISSUE THREAD

**Issue by cheese** [ndevilla/iniparser#98]
Upstream iniparser does not provide a 'make install' support. Downstream distributions may install the header files to different places.
For example, Ubuntu installs header files to /usr/include/iniparser but Fedora installs them to /usr/include directly.
It would hard for distributions to negotiate with each other to decide a common path. It's better for upstream to make this decision.

**Comment by lmoellendorf** [comment]
Please have a look at [iniparser-meta](https://gitlab.com/iniparser/iniparser-meta).
Feel free to add an issue there if it does not fit your needs.
